name: APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - variant: GithubDebug
            task: assembleGithubDebug
            path: app/build/outputs/apk/github/debug/*.apk
            artifact: chemsearch-github-debug
          - variant: GithubRelease
            task: assembleGithubRelease
            path: app/build/outputs/apk/github/release/*.apk
            artifact: chemsearch-github-release
          - variant: FdroidDebug
            task: assembleFdroidDebug
            path: app/build/outputs/apk/fdroid/debug/*.apk
            artifact: chemsearch-fdroid-debug
          - variant: FdroidRelease
            task: assembleFdroidRelease
            path: app/build/outputs/apk/fdroid/release/*.apk
            artifact: chemsearch-fdroid-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :app:${{ matrix.task }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}
